### ISSUE TITLE
i2c slave AK8963

### ISSUE THREAD

**Issue by danielss24** [thisisG/MPU6050-I2C-Python-Class#2]
Hi, im currently working with this code and i need to use also slave address in order to get info from MPU9250 with magnetometer AK8963, any idea how should i put the configuration to use both? 

I am using this code for the magnetometer: https://github.com/FaBoPlatform/FaBo9AXIS-MPU9250-Python/blob/master/FaBo9Axis_MPU9250/MPU9250.py

Thank u

**Comment by thisisG** [comment]
Sorry I do not know. I do not even have access to any hardware any longer so cannot be of much help. 
Since the MPU9250 contains both the jist of the code here should work, but the i2c communication part/sampling you'd have to figure out on your own I'm afraid. :-(
